# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://ceniklab.github.io"
baseurl: ""


# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Cenik Lab

# Short description of your site
description: Translation Control and Functional Genomics

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Team: 
   - Lab Members: "team.html"
   - Lab Life: "lab_life.html"
   - Collaborators: "collaborators.html"
   - Alumni: "alumni.html"
  Software:
    - Ribo: "https://ribosomeprofiling.github.io/"
  Publications:
   - Selected Publications: "publications.html"
   - Pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=cenik+c"
   - Google Scholar: "https://scholar.google.com/citations?user=DedRqJIAAAAJ"
  Research: "research"
  Join Us: "jobs"
  Contact: "contact"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: img/logo.svg
title-img-link: https://www.utexas.edu/


# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

# Original
# navbar-col: "#F5F5F5"

navbar-col: "#e6ebf4"
navbar-text-col: "#404040"

#Original
#navbar-children-col: "#F5F5F5"

navbar-children-col: "#f5f7fa"

page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"

#Original
#footer-col: "#F5F5F5"
#fdf6f1
footer-col: "#e6ebf4"

footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Can Cenik

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
#  rss: true
  email: "ccenik@stanford.edu"
  github: cancenik
  linkedin: can-cenik-021b3451
#  telephone: +14159998888
  twitter: CenikLab

# Select which share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  google: false
  linkedin: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "CenikLab"

# --- Web Statistics Section --- #

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-120211245-1"

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: none
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

collections:
  publications_other:
    output: true
  publications_cancer:
    output: true
  publications_functional_genomics:
    output: true
  publications_RBP:
    output: true
  publications_software:
    output: true
  publications_translation_control:
    output: true  
  team:
    output: true
  collaborators:
    output: true
  alumni:
    output: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

gems:
  jekyll-maps

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-maps

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
